### ISSUE TITLE
CSS parsing of valid CSS files fails

### ISSUE THREAD

**Issue by mscofield0** [w3c/epubcheck#1333]
I use TailwindCSS with my epub project to style the book. However, stuff that are usually legal that Tailwind produces, don't pass the epub checker's validator. I assume that the parser doesn't fully conform to the CSS standard, or there are some limitations in the EPUB standard that I'm missing.

- An error occurred while parsing the CSS: Token "]" not allowed here.
```css
/*
__________________
           vvvvvvv  */
abbr:where([title]) {
  -webkit-text-decoration: underline dotted;
          text-decoration: underline dotted;
}
```

- Empty CSS variables fail parsing too (e.g. `--tw-color: ;`)
- CSS font selector declaration uses unexpected font-size value "unset"
```css
[type='file'] {
  background: unset;
  border-color: inherit;
  border-width: 0;
  border-radius: 0;
  padding: 0;
  font-size: unset; /* <------- */
  line-height: inherit;
}
```
