### ISSUE TITLE
CSS properties can be misspelled.

### ISSUE THREAD

**Issue by jenstroeger** [w3c/epubcheck#935]
I noticed that there are several closely related CSS issues that are currently filed here:

 1. General CSS validation and syntax checking (issue https://github.com/w3c/epubcheck/issues/149).
 2. Missing semicolons are not reported, i.e. syntax error (issue https://github.com/w3c/epubcheck/issues/243).
 3. Incorrect media-types are not detected (issue https://github.com/w3c/epubcheck/issues/302).
 4. Does not recognize custom properties (issue https://github.com/w3c/epubcheck/issues/790).

I’d argue that these are all token and syntax errors, and I would like to add yet another one that I noticed today:
```css
  p {
    font-size: 1em;
    margin-top: 1.5em;
    margin-bottm: 0.2em;  /* misspelled! */
    text-align: left;
  } 
```
The `margin-bottm` is misspelled which technically is a syntax error (invalid token). I would vote that this should be reported as an error by epubcheck.
